name: Publish on Docker
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build container
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          push: true
          tags: KarChunT/publicpackages:latest
